version: '3.1'
services:
  metabase:
    image: metabase/metabase:latest
    volumes:
      - /python-app/data/db:/metabase-data
    ports:
      - "3000:3000"
#    environment:
#      MB_DB_TYPE: "mysql"
#      MB_DB_HOST: "db"
#      MB_DB_HOST: "metabase-db-1"
#      MB_DB_PORT: "3306"
#      MB_DB_NAME: "metabase"
#      MB_DB_DBNAME: "metabase"
#      MB_DB_USER: "dba"
#      MB_DB_PASS: "A1YTsqilzHkUQ4"
    depends_on:
      - db

#    secrets:
#      - db_credentials
  db:
    image: mysql
#    command: --default-authentication-plugin=mysql_native_password
    command: --default-authentication-plugin=caching_sha2_password
    deploy:
#    ports:
#      - 3306:3306
    environment:
#      MYSQL_ROOT_PASSWORD: "EhTbmTtNS5KXO+U7"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: dba
      MYSQL_DATABASE: metabase    
      MYSQL_PASSWORD: "A1YTsqilzHkUQ4"
#    volumes:
#      - /Users/A347826/opt/docker/volumes/mysql:/var/lib/mysql

#  adminer:
#    image: adminer
#    ports:
#      - 8080:8080
